version: "3.7"
services:
  db:
    image: postgres:13
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations/:/docker-entrypoint-initdb.d/
