@startuml

folder domain [
**Domain**
---
Domain Entities
Value-Objects
Repository interfaces
]

folder application [
**Application**
---
REST Web API
Commands
Queries
]

folder infrastructure [
**Infrastructure**
---
Repository implementations
Data Access Objects
Domain Entity Projections
]

infrastructure -u-> domain : depends on
application -u-> domain : depends on
application->infrastructure : depends on

@enduml