@startuml

component rest_api as "REST API"

package "Write model" {
  database event_store as "Event\nStore" #Lightblue
  [Command] -> [Domain Entity\nRepository]
  [Domain Entity\nRepository] -> event_store
}

package "Read model" {
  database entity_projections as "Domain Entity\nProjections" #Lightblue

  [Query] -> [Domain Entity\nProjection Repository]
  [Domain Entity\nProjection Repository] .> [Query]

  [Domain Entity\nProjection Repository] -> entity_projections
  entity_projections .> [Domain Entity\nProjection Repository]

  event_store -d-> [Domain Entity\nProjector]

  [Domain Entity\nProjector] -> entity_projections
}

rest_api --> [Command]
rest_api --> [Query]

@enduml