@startuml
title Creating a new account (work in progress)

participant User
participant AccountController
participant CreateAccountCommand
participant Account
participant AccountCreatedEvent
participant AccountRepository
participant EventStore
database events

User -> AccountController : createAccount()
AccountController -> CreateAccountCommand : handle()
CreateAccountCommand -> Account : account = new Account()
Account -> AccountCreatedEvent : new()
AccountCreatedEvent --> Account
Account --> CreateAccountCommand
CreateAccountCommand -> AccountRepository : save(account)
AccountRepository -> EventStore : appendEvent(account.pendingEvents[])
EventStore -> events : INSERT

events --> EventStore
EventStore --> AccountRepository
AccountRepository --> CreateAccountCommand
CreateAccountCommand --> AccountController
AccountController --> User
@enduml