@startuml
title Retrieving an existing account (work in progress)

participant User
participant AccountController
participant GetAccountQuery
participant AccountRepository
participant EventStore
database events
participant Account

User -> AccountController : getAccount(id)
AccountController -> GetAccountQuery : handle(id)
GetAccountQuery -> AccountRepository : findById(id)
AccountRepository -> EventStore : getEventStream(aggregateId)
EventStore -> events : SELECT
events --> EventStore
EventStore --> AccountRepository
AccountRepository -> Account : loadFromEvents(events, version)
Account -> Account : mutate(event)
Account --> AccountRepository
AccountRepository --> GetAccountQuery
GetAccountQuery --> AccountController
AccountController -> User
@enduml